# Generated by Django 5.1.4 on 2024-12-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(default=None, max_length=500)),
                ('periodo', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
