# Generated by Django 5.1.4 on 2024-12-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('ONLINE', 'ONLINE')], default='PRESENCIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.CharField(choices=[('MATUTINO', 'MATUTINO'), ('NOTURNO', 'NOTURNO'), ('DIURNO', 'DIURNO')], default='MATUTINO', max_length=20),
        ),
    ]
