# Generated by Django 5.1.4 on 2024-12-10 14:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horaria')),
                ('curso', models.ManyToManyField(to='app.curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('disciplina', models.ManyToManyField(blank=True, to='app.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('ABERTA', 'ABERTA'), ('FECHADA', 'FECHADA'), ('PRORROGADA', 'PRORROGADA')], max_length=10)),
                ('atividade', models.CharField(choices=[('ATV1', 'ATV1'), ('ATV2', 'ATV2'), ('ATV3', 'ATV3'), ('ATV4', 'ATV4')], max_length=4, verbose_name='Atividade Complementar')),
                ('dt_inicio', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data inicio')),
                ('dt_final', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Fim')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividade', to='app.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividade', to='app.professor')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('Turma A', 'Turma A'), ('Turma B', 'Turma B'), ('Turma C', 'Turma C'), ('Turma D', 'Turma D')], default=None, max_length=7, verbose_name='Turma')),
                ('semestre', models.CharField(choices=[('PRI-SEM', 'PRIMEIRO SEMESTRE'), ('SEG-SEM', 'SEGUNDO SEMESTRE'), ('TER-SEM', 'TERCEIRO SEMESTRE'), ('QUA-SEM', 'QUARTO SEMESTRE')], default='PRI-SEM', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='app.curso')),
                ('disciplina', models.ManyToManyField(to='app.disciplina')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Atv', 'Ativa'), ('Canc', 'Cancelada'), ('An', 'Em Analise'), ('So', 'Solicitada')], default=None, max_length=4)),
                ('dt_inicio', models.DateField()),
                ('dt_final', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='app.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='app.curso')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='app.turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('turma', 'curso', 'semestre'), name='unique_turma_curso_semestre'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('turma', 'curso'), name='unique_turma'),
        ),
    ]
